name: build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - main
      - build_test
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7,linux/arm64
